google:
  calendar:
    clientId: replaceit
    authUri: https://accounts.google.com/o/oauth2/auth
    tokenUri: https://oauth2.googleapis.com/token
    clientSecret: replaceit
    redirectUris: http://localhost:8080/callback
    calendarId: replaceit


